package dev.audioscope;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.media.projection.MediaProjectionManager;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.telecom.TelecomManager;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;

public class MainActivity extends androidx.appcompat.app.AppCompatActivity {
    private static final int BG=0xff141019,CARD=0xff231c2e,INK=0xffeee7f5,MUTED=0xffb1a6bd,RED=0xffffb4ab;
    private int ACCENT;
    private final SourceMonitor monitors=new SourceMonitor();private final Map<String,Row> sourceRows=new HashMap<>();private Button recordAll;private final Map<String,Spinner> sourceFormats=new HashMap<>();private boolean foreground;private long lastMonitor;
    private final Handler handler=new Handler(Looper.getMainLooper());private LinearLayout root,body,nav;private TextView engine,time,sessionState,logView,inspectView;private Button record,pause;private EditText logFilter;private int tab=0,lastMode=-1;private String[] pendingSources;
    private final LinkedHashSet<String> selected=new LinkedHashSet<>();private final Map<String,Row> rows=new HashMap<>();private boolean destroyed;
    private static final class Row {TextView state,stats;Button button;WaveformView wave;CheckBox selected;}
    public void onCreate(Bundle saved){super.onCreate(saved);if(saved!=null)tab=saved.getInt("tab",0);selected.addAll(ScopeApp.prefs().getStringSet("selected",new LinkedHashSet<>(Arrays.asList("mic","voice_playback"))));getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);render();}
    protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);b.putInt("tab",tab);}
    public void onResume(){super.onResume();foreground=true;if(tab==5)enableMeters();handler.post(update);}
    public void onPause(){super.onPause();foreground=false;monitors.disable();handler.removeCallbacks(update);}
    public void onDestroy(){destroyed=true;handler.removeCallbacksAndMessages(null);super.onDestroy();}
    private int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    private LinearLayout column(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}
    private LinearLayout horizontal(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private TextView text(String value,int size,int color){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(3),0,dp(3));return t;}
    private TextView title(String s){TextView t=text(s,22,INK);t.setTypeface(null,Typeface.BOLD);return t;}
    private GradientDrawable background(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius+6));return d;}
    private LinearLayout card(){LinearLayout l=column();l.setPadding(dp(16),dp(14),dp(16),dp(14));l.setBackground(background(CARD,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.bottomMargin=dp(12);l.setLayoutParams(p);return l;}
    private Button button(String label,int color,Runnable action){com.google.android.material.button.MaterialButton b=new com.google.android.material.button.MaterialButton(this);b.setText(label);b.setAllCaps(false);b.setTextSize(13);b.setTextColor(color==ACCENT?BG:INK);b.setTypeface(null,Typeface.BOLD);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(color==ACCENT?ACCENT:0xff423352));b.setCornerRadius(dp(24));b.setInsetTop(0);b.setInsetBottom(0);b.setMinHeight(dp(44));b.setPadding(dp(12),dp(6),dp(12),dp(6));b.setOnClickListener(v->action.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(46));p.topMargin=dp(8);b.setLayoutParams(p);return b;}
    private void two(LinearLayout parent,Button a,Button b){LinearLayout row=horizontal();LinearLayout.LayoutParams pa=new LinearLayout.LayoutParams(0,dp(46),1);pa.setMargins(0,dp(8),dp(5),0);a.setLayoutParams(pa);LinearLayout.LayoutParams pb=new LinearLayout.LayoutParams(0,dp(46),1);pb.setMargins(dp(5),dp(8),0,0);b.setLayoutParams(pb);row.addView(a);row.addView(b);parent.addView(row);}
    private void section(String s){TextView t=text(s,11,MUTED);t.setTypeface(null,Typeface.BOLD);t.setLetterSpacing(.16f);t.setPadding(0,dp(16),0,dp(10));body.addView(t);}
    private void render(){
        ACCENT=ThemePalette.accent(this);
        rows.clear();sourceRows.clear();sourceFormats.clear();if(tab!=5)monitors.disable();root=column();root.setBackgroundColor(BG);root.setPadding(dp(20),dp(8),dp(20),0);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(20),dp(8)+i.getSystemWindowInsetTop(),dp(20),i.getSystemWindowInsetBottom());return i;});setContentView(root);
        LinearLayout head=horizontal();TextView name=title("AudioScope");head.addView(name,new LinearLayout.LayoutParams(0,-2,1));TextView badge=text("LOCAL / OFFLINE",9,ACCENT);badge.setTypeface(null,Typeface.BOLD);badge.setLetterSpacing(.12f);head.addView(badge);root.addView(head);engine=text(ScopeApp.backend,11,MUTED);root.addView(engine);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.setClipToPadding(false);body=column();body.setPadding(0,dp(18),0,dp(20));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        nav=horizontal();String[] tabs={"Capture","Sources","Sessions","Routing","Lab","Settings"};int[] tabIds={0,5,1,2,3,4};for(int i=0;i<tabs.length;i++){final int index=tabIds[i];TextView n=text(tabs[i],10,index==tab?ACCENT:MUTED);n.setGravity(Gravity.CENTER);n.setTypeface(null,Typeface.BOLD);n.setPadding(0,dp(20),0,dp(20));if(index==tab)n.setBackground(background(0xff3b2d4e,24));n.setContentDescription(tabs[i]+" tab");n.setOnClickListener(v->{tab=index;render();});nav.addView(n,new LinearLayout.LayoutParams(0,-2,1));}root.addView(nav);
        switch(tab){case 0:capture();break;case 1:sessions();break;case 2:routing();break;case 3:lab();break;case 4:settings();break;case 5:sources();break;}
    }
    private void enableMeters(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED){monitors.enable();monitors.refresh();}else requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},24);}
    private Button recordDot(String description,Runnable action){Button b=button("●",CARD,action);b.setTextSize(26);b.setTextColor(0xff938d9c);b.setContentDescription(description);((com.google.android.material.button.MaterialButton)b).setCornerRadius(dp(16));return b;}
    private void sources(){
        body.addView(title("Sources"));LinearLayout heading=horizontal();recordAll=recordDot("Record all sources",()->{if(CaptureService.active())CaptureService.instance.stopSession();else startRecord(Source.ALL.stream().map(s->s.id).toArray(String[]::new));});heading.addView(recordAll,new LinearLayout.LayoutParams(dp(52),dp(52)));TextView all=text("Record all",19,INK);all.setPadding(dp(12),0,0,0);heading.addView(all);body.addView(heading);body.addView(text("Live monitoring • no files until you press record",12,MUTED));body.addView(text("Every listed route is attempted. Android may silence concurrent inputs or block protected routes. Remote submix can redirect speaker output.",11,MUTED));
        for(Source source:Source.ALL){Row row=new Row();sourceRows.put(source.id,row);LinearLayout c=card(),line=horizontal();row.button=recordDot("Record "+source.title,()->{CaptureService.Track t=CaptureService.tracks.get(source.id);if(CaptureService.active()&&t!=null&&t.running){ScopeApp.IO.execute(()->{t.stop();try{t.done.await(6,java.util.concurrent.TimeUnit.SECONDS);}catch(Exception ignored){}if(CaptureService.active()&&CaptureService.tracks.values().stream().noneMatch(x->x.running))CaptureService.instance.stopSession();});}else if(CaptureService.active()){ScopeApp.IO.execute(()->{monitors.release(source.id);if(CaptureService.active())CaptureService.instance.startTrack(source.id);});}else startRecord(new String[]{source.id});});line.addView(row.button,new LinearLayout.LayoutParams(dp(52),dp(52)));row.wave=new WaveformView(this,ACCENT);LinearLayout.LayoutParams wave=new LinearLayout.LayoutParams(0,dp(64),1);wave.leftMargin=dp(14);line.addView(row.wave,wave);c.addView(line);c.addView(text(source.title,15,INK));row.state=text("WAITING FOR MONITOR",10,MUTED);c.addView(row.state);row.stats=text("",10,MUTED);c.addView(row.stats);String[] formats={"WAV","PCM","AAC","Opus"};String current=ScopeApp.prefs().getString("format_"+source.id,ScopeApp.prefs().getString("codec","WAV"));int index=Arrays.asList(formats).indexOf(current);Spinner format=spinner(formats,Math.max(0,index));sourceFormats.put(source.id,format);format.setContentDescription(source.title+" audio format");format.setEnabled(!CaptureService.active());format.setOnItemSelectedListener(listener(i->ScopeApp.prefs().edit().putString("format_"+source.id,formats[i]).apply()));LinearLayout formatLine=horizontal();formatLine.addView(text("Audio format",11,MUTED),new LinearLayout.LayoutParams(0,-2,1));formatLine.addView(format,new LinearLayout.LayoutParams(dp(112),dp(40)));c.addView(formatLine);body.addView(c);}
        if(foreground)enableMeters();
    }
    private void updateSources(){for(Spinner format:sourceFormats.values())if(format.isEnabled()==CaptureService.active())format.setEnabled(!CaptureService.active());if(System.currentTimeMillis()-lastMonitor>1000){lastMonitor=System.currentTimeMillis();monitors.refresh();}int allColor=CaptureService.active()?0xfff45b79:0xff938d9c;if(recordAll.getCurrentTextColor()!=allColor)recordAll.setTextColor(allColor);for(Map.Entry<String,Row> entry:sourceRows.entrySet()){CaptureService.Track saved=CaptureService.tracks.get(entry.getKey());boolean recording=CaptureService.active()&&saved!=null&&saved.running;CaptureService.Track t=recording?saved:monitors.get(entry.getKey());Row row=entry.getValue();int dot=recording?0xfff45b79:0xff938d9c;if(row.button.getCurrentTextColor()!=dot)row.button.setTextColor(dot);row.button.setContentDescription((recording?"Stop ":"Record ")+Source.get(entry.getKey()).title);row.wave.update(t);if(t!=null){setIfChanged(row.state,(recording?"RECORDING • ":"")+t.state);setIfChanged(row.stats,t.error.isEmpty()?String.format(Locale.US,"%.1f dBFS • peak %.0f%% • %,d frames",t.db,t.peak*100,t.frames):t.error);}else setIfChanged(row.state,"WAITING FOR MONITOR");}}
    private void capture(){
        body.addView(title("Your audio. Your controls."));body.addView(text("Choose sources. See the signal. Keep every track.",13,MUTED));
        LinearLayout hero=card();time=text(CaptureService.formatTime(CaptureService.elapsedMs()),38,INK);time.setTypeface(Typeface.MONOSPACE,Typeface.BOLD);hero.addView(time);sessionState=text(CaptureService.active()?"SESSION ACTIVE":"READY • "+selected.size()+" SOURCES SELECTED",11,ACCENT);hero.addView(sessionState);
        record=button(CaptureService.active()?"Stop & save session":"●  Record selected sources",ACCENT,()->{if(CaptureService.active())CaptureService.instance.stopSession();else startRecord(selected.toArray(new String[0]));});hero.addView(record);pause=button(CaptureService.paused?"Resume":"Pause",CARD,()->{if(CaptureService.active())CaptureService.instance.togglePause();});two(hero,pause,button("Add bookmark",CARD,()->{if(CaptureService.active())prompt("Bookmark label","",s->CaptureService.instance.mark(s));else toast("Start a session first");}));body.addView(hero);
        LinearLayout presets=card();presets.addView(text("CAPTURE PRESET",10,MUTED));String[] names={"Custom selection","Voice memo","Teams / app call","Carrier call","Carrier separated","Wi-Fi Calling probe","Media + microphone","Playback diagnostics"};Spinner spinner=spinner(names,0);spinner.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int position,long id){if(position>0){String[][] ids={{},{"mic"},{"mic","voice_playback"},{"voice_call"},{"uplink","downlink"},{"mic","voice_call","uplink","downlink","voice_playback","media"},{"media","mic"},{"media","game","voice_playback","navigation","assistant","alarm","notification"}};selected.clear();selected.addAll(Arrays.asList(ids[position]));saveSelection();for(Source s:Source.ALL)if(rows.containsKey(s.id))rows.get(s.id).selected.setChecked(selected.contains(s.id));}}});presets.addView(spinner);two(presets,button("Save preset",CARD,()->prompt("Preset name","My setup",this::savePreset)),button("Load preset",CARD,this::loadPreset));body.addView(presets);
        String group="";for(Source s:Source.ALL){if(!group.equals(s.group)){group=s.group;section(group);}sourceRow(s);}
        body.addView(text("Loopback policies work best when armed before starting playback or joining Teams. Signal health reflects actual PCM, not a successful API call.",12,MUTED));
    }
    private void sourceRow(Source source){
        LinearLayout c=card();Row row=new Row();rows.put(source.id,row);LinearLayout heading=horizontal();row.selected=new CheckBox(this);row.selected.setButtonTintList(android.content.res.ColorStateList.valueOf(source.color));row.selected.setChecked(selected.contains(source.id));row.selected.setContentDescription("Select "+source.title);row.selected.setOnCheckedChangeListener((v,b)->{if(b)selected.add(source.id);else selected.remove(source.id);saveSelection();});heading.addView(row.selected,new LinearLayout.LayoutParams(dp(34),dp(36)));TextView label=text(source.title,16,INK);label.setTypeface(null,Typeface.BOLD);heading.addView(label,new LinearLayout.LayoutParams(0,-2,1));row.state=text("IDLE",9,MUTED);heading.addView(row.state);c.addView(heading);c.addView(text(source.detail,11,MUTED));row.wave=new WaveformView(this,source.color);c.addView(row.wave,new LinearLayout.LayoutParams(-1,dp(64)));row.stats=text("−∞ dBFS   •   0 frames",10,MUTED);row.stats.setTypeface(Typeface.MONOSPACE);c.addView(row.stats);
        row.button=button("Record this source",CARD,()->{CaptureService.Track t=CaptureService.tracks.get(source.id);if(t!=null&&t.running){ScopeApp.IO.execute(t::stop);return;}if(source.id.equals("remote_submix"))new AlertDialog.Builder(this).setTitle("Remote submix experiment").setMessage("This route can redirect audio and silence normal playback. Stop the source to restore output.").setPositiveButton("Record",(d,w)->recordOne(source.id)).setNegativeButton("Cancel",null).show();else recordOne(source.id);});
        if(source.playback())two(c,row.button,button("Arm loopback",CARD,()->arm(source)));else c.addView(row.button);body.addView(c);
    }
    private void recordOne(String id){if(CaptureService.active()){CaptureService.instance.startTrack(id);}else startRecord(new String[]{id});}
    private void arm(Source s){if(ScopeApp.bridge==null){toast("Connect the privileged helper in Settings");return;}if(CaptureService.active()){toast("Arm policies before recording; source settings are frozen during a session");return;}ScopeApp.IO.execute(()->{try{String result=ScopeApp.bridge.arm(s.id,ScopeApp.prefs().getInt("rate",48000),ScopeApp.prefs().getInt("channels",1),ScopeApp.prefs().getInt("uidFilter",-1));ScopeApp.log(result.startsWith("FAILED")?"ERROR":"INFO",result);handler.post(()->toast(result));}catch(Throwable e){ScopeApp.log("ERROR",ShellBridge.root(e));}});}
    private void saveSelection(){ScopeApp.prefs().edit().putStringSet("selected",new LinkedHashSet<>(selected)).apply();}
    private void startRecord(String[] sources){
        if(sources.length==0){toast("Select at least one source");return;}if(CaptureService.stopping&&CaptureService.instance!=null){toast("Finalizing previous session");return;}pendingSources=sources;
        if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},21);return;}
        if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},22);return;}
        boolean needsProjection=ScopeApp.bridge==null&&Arrays.stream(sources).anyMatch(s->{Source x=Source.get(s);return x.playback()&&(x.usage==0||x.usage==1||x.usage==14);});
        if(needsProjection){startActivityForResult(getSystemService(MediaProjectionManager.class).createScreenCaptureIntent(),31);return;}launchCapture(null);
    }
    private void launchCapture(Intent data){monitors.disable();ScopeApp.IO.execute(()->{monitors.stop();handler.post(()->launchCaptureReady(data));});}
    private void launchCaptureReady(Intent data){Intent intent=new Intent(this,CaptureService.class).setAction("RECORD").putExtra("sources",pendingSources);if(data!=null)intent.putExtra("projection",data);startForegroundService(intent);handler.postDelayed(()->{if(tab==0||tab==5)render();},500);}
    public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==24){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){monitors.enable();monitors.refresh();}else toast("Microphone permission is required for live monitoring");}else if(r==21){if(g.length>0&&g[0]==0)startRecord(pendingSources);else toast("Microphone permission is required for the recording foreground service");}else if(r==22){boolean projection=ScopeApp.bridge==null&&Arrays.stream(pendingSources).anyMatch(s->Source.get(s).playback()&&(Source.get(s).usage==0||Source.get(s).usage==1||Source.get(s).usage==14));if(projection)startActivityForResult(getSystemService(MediaProjectionManager.class).createScreenCaptureIntent(),31);else launchCapture(null);}}
    protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==31){if(result==RESULT_OK&&data!=null)launchCapture(data);else toast("Playback consent was declined");}}
    private final Runnable update=new Runnable(){public void run(){if(destroyed)return;setIfChanged(engine,(ScopeApp.bridge!=null?"● ":"○ ")+ScopeApp.backend);if(tab==0){setIfChanged(time,CaptureService.formatTime(CaptureService.elapsedMs()));setIfChanged(record,CaptureService.active()?"■  Stop & save session":"●  Record selected sources");setIfChanged(pause,CaptureService.paused?"Resume":"Pause");pause.setEnabled(CaptureService.active());setIfChanged(sessionState,CaptureService.active()?(CaptureService.paused?"PAUSED":"SESSION ACTIVE")+" • "+CaptureService.tracks.values().stream().filter(t->t.running).count()+" RECORDING":CaptureService.stopping&&CaptureService.instance!=null?"FINALIZING":"READY • "+selected.size()+" SOURCES SELECTED");for(Map.Entry<String,Row> e:rows.entrySet()){CaptureService.Track t=CaptureService.tracks.get(e.getKey());Row row=e.getValue();row.wave.update(t);if(t!=null){setIfChanged(row.state,t.state);row.state.setTextColor(t.state.equals("LIVE")?ACCENT:t.state.equals("FAILED")||t.state.equals("BLOCKED")||t.state.equals("SILENT")?RED:MUTED);setIfChanged(row.stats,t.error.isEmpty()?String.format(Locale.US,"%.1f dBFS  •  peak %.0f%%  •  zero %.0f%%\n%,d frames  •  %d drops  •  %d clips",t.db,t.peak*100,(1-t.nonzero)*100,t.frames,t.dropped,t.clipped):t.error);setIfChanged(row.button,t.running?"Stop this source":"Record this source");}}}
        if(tab==5)updateSources();if(tab==3&&logView!=null)setIfChanged(logView,ScopeApp.logText(logFilter==null?"":logFilter.getText().toString()));AudioManager audio=getSystemService(AudioManager.class);int mode=audio.getMode();if(mode!=lastMode){if(lastMode!=-1)ScopeApp.log("INFO","Audio mode changed: "+lastMode+" → "+mode);lastMode=mode;}handler.postDelayed(this,200);}};
    private void sessions(){
        body.addView(title("Session library"));body.addView(text("Original tracks, exports, timing, and diagnostics.",13,MUTED));if(!CaptureService.exportStatus.isEmpty())body.addView(text(CaptureService.exportStatus,12,ACCENT));body.addView(button("Refresh library",CARD,()->render()));File[] folders=ScopeApp.sessions().listFiles(File::isDirectory);if(folders==null||folders.length==0){LinearLayout empty=card();empty.addView(text("Your first recording lives here.",18,INK));empty.addView(text("Start a capture or run the pipeline self-test in Lab.",13,MUTED));body.addView(empty);return;}Arrays.sort(folders,Comparator.comparing(File::getName).reversed());
        for(File folder:folders){LinearLayout c=card();c.addView(text(folder.getName(),16,INK));File[] files=folder.listFiles();long size=0;int count=0;if(files!=null)for(File f:files){size+=f.length();if(f.getName().endsWith(".wav"))count++;}c.addView(text(count+" WAV files • "+String.format(Locale.US,"%.1f MiB",size/1048576.0),12,MUTED));two(c,button("Browse / play",CARD,()->browse(folder)),button("Share session ZIP",CARD,()->{if(CaptureService.session!=null&&CaptureService.session.equals(folder)){toast("Stop this session before exporting");return;}ScopeApp.IO.execute(()->{try{File zip=Exports.zip(folder);handler.post(()->share(zip));}catch(Throwable e){ScopeApp.log("ERROR",e.toString());}});}));body.addView(c);}
    }
    private void browse(File folder){File[] files=folder.listFiles(File::isFile);if(files==null)return;Arrays.sort(files,Comparator.comparing(File::getName));String[] labels=new String[files.length];for(int i=0;i<files.length;i++)labels[i]=files[i].getName()+"  ("+files[i].length()/1024+" KiB)";new AlertDialog.Builder(this).setTitle(folder.getName()).setItems(labels,(d,w)->{File f=files[w];if(f.getName().endsWith(".wav")||f.getName().endsWith(".m4a")||f.getName().endsWith(".webm"))new AlertDialog.Builder(this).setTitle(f.getName()).setItems(new String[]{"Play in AudioScope","Share file"},(a,b)->{if(b==0)play(f);else share(f);}).show();else if(f.getName().endsWith(".json")||f.getName().endsWith(".log"))try{showText(f.getName(),Exports.read(f));}catch(Exception e){toast(e.toString());}else share(f);}).show();}
    private void play(File f){try{MediaPlayer p=new MediaPlayer();p.setDataSource(f.getPath());p.prepare();p.start();AlertDialog dialog=new AlertDialog.Builder(this).setTitle(f.getName()).setMessage("Playing local audio • "+p.getDuration()/1000+" seconds").setPositiveButton("Stop",null).create();dialog.setOnDismissListener(d->{try{p.stop();}catch(Exception ignored){}p.release();});dialog.show();}catch(Exception e){toast("Playback: "+e.getMessage());}}
    private void share(File f){Intent i=new Intent(Intent.ACTION_SEND).setType(getContentResolver().getType(ShareProvider.uri(f))).putExtra(Intent.EXTRA_STREAM,ShareProvider.uri(f)).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.setClipData(ClipData.newRawUri("AudioScope export",ShareProvider.uri(f)));startActivity(Intent.createChooser(i,"Share "+f.getName()));}
    private void routing(){
        body.addView(title("Output routing"));body.addView(text("Original WAVs always stay separate. Create additional outputs from the same capture.",13,MUTED));body.addView(text("Changes apply to the next session. Gain and mute affect exported mixes; originals retain captured PCM.",12,ACCENT));
        LinearLayout outputs=card();toggle(outputs,"Stereo pair WAV","L / R assignments below", "stereo",false);toggle(outputs,"Normalized mono mix","Weighted sum with headroom", "mix",false);toggle(outputs,"True multitrack MKA","One named PCM audio track per source", "mka",false);body.addView(outputs);
        LinearLayout pair=card();pair.addView(text("STEREO ASSIGNMENT",11,MUTED));sourceSpinner(pair,"Left channel","routeLeft","mic");sourceSpinner(pair,"Right channel","routeRight","voice_playback");pair.addView(button("Swap left / right",CARD,()->{if(!settingsEditable())return;String l=ScopeApp.prefs().getString("routeLeft","mic"),r=ScopeApp.prefs().getString("routeRight","voice_playback");ScopeApp.prefs().edit().putString("routeLeft",r).putString("routeRight",l).apply();render();}));body.addView(pair);
        section("MIX GAIN / MUTE");for(Source s:Source.ALL){LinearLayout c=card();c.addView(text(s.title,14,INK));TextView value=text("Gain "+ScopeApp.prefs().getFloat("gain_"+s.id,1)+"×",11,MUTED);c.addView(value);SeekBar slider=new SeekBar(this);slider.setMax(200);slider.setProgress(Math.round(ScopeApp.prefs().getFloat("gain_"+s.id,1)*100));slider.setEnabled(!CaptureService.active());slider.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar b){}public void onStopTrackingTouch(SeekBar b){}public void onProgressChanged(SeekBar b,int n,boolean user){if(user){ScopeApp.prefs().edit().putFloat("gain_"+s.id,n/100f).apply();value.setText("Gain "+n/100f+"×");}}});c.addView(slider);toggle(c,"Mute in exports","Keep original source recording", "mute_"+s.id,false);body.addView(c);}
        body.addView(text("Stereo / mono exports align source start timestamps and estimate clock drift. MKA preserves each source's native sample clock and initial offset. Raw streams and per-chunk timing remain available for precise analysis.",12,MUTED));
    }
    private void lab(){
        body.addView(title("Audio laboratory"));body.addView(text("Measure the route. Inspect the permissions. Keep the evidence.",13,MUTED));LinearLayout tests=card();tests.addView(text("RECORDING TESTS",11,MUTED));tests.addView(button("5-second probe • selected sources",ACCENT,()->{if(CaptureService.active()){toast("Stop the active session first");return;}startRecord(selected.toArray(new String[0]));waitThenStop(5);}));tests.addView(button("Sequential source sweep • selected",CARD,this::sweep));tests.addView(button("Run offline pipeline self-test",CARD,this::selfTest));tests.addView(button("Repair interrupted WAV headers",CARD,this::repair));body.addView(tests);
        LinearLayout inspector=card();inspector.addView(text("LIVE AUDIO INSPECTOR",11,MUTED));two(inspector,button("Inspect device / shell",CARD,this::inspect),button("Export diagnostics",CARD,this::diagnosticExport));inspectView=text("Tap Inspect to collect current mode, device routes, capture configurations, shell permissions, and AudioService state.",12,MUTED);inspectView.setTypeface(Typeface.MONOSPACE);inspectView.setTextIsSelectable(true);inspector.addView(inspectView);body.addView(inspector);
        LinearLayout logs=card();logs.addView(text("EVENT LOG",11,MUTED));logFilter=input("Filter: source, error, mode…","",false);logs.addView(logFilter);logView=text(ScopeApp.logText(""),10,MUTED);logView.setTypeface(Typeface.MONOSPACE);logView.setTextIsSelectable(true);logs.addView(logView);body.addView(logs);
    }
    private void waitThenStop(int seconds){handler.postDelayed(new Runnable(){int attempts;public void run(){if(CaptureService.active()){handler.postDelayed(()->{if(CaptureService.active())CaptureService.instance.stopSession();},seconds*1000L);}else if(attempts++<120)handler.postDelayed(this,500);}},500);}
    private void sweep(){if(CaptureService.active()){toast("Stop the active session first");return;}if(selected.isEmpty()){toast("Select sources in Capture");return;}String[] ids=selected.toArray(new String[0]);startRecord(new String[]{ids[0]});handler.postDelayed(new Runnable(){int attempts;public void run(){if(CaptureService.active()){ScopeApp.IO.execute(()->{for(int i=0;i<ids.length;i++){if(!CaptureService.active())break;if(i>0)CaptureService.instance.startTrack(ids[i]);ScopeApp.log("INFO","Sweep "+(i+1)+"/"+ids.length+": "+ids[i]);try{Thread.sleep(5000);}catch(InterruptedException e){break;}CaptureService.Track t=CaptureService.tracks.get(ids[i]);if(t!=null){t.stop();try{t.done.await(5,java.util.concurrent.TimeUnit.SECONDS);}catch(Exception ignored){}}}if(CaptureService.active())CaptureService.instance.stopSession();});}else if(attempts++<120)handler.postDelayed(this,500);}},500);}
    private void inspect(){ScopeApp.IO.execute(()->{String report=deviceReport();try{if(ScopeApp.bridge!=null)report+="\n\nSHELL INSPECTION\n"+ScopeApp.bridge.inspect();else report+="\nShell helper not connected.";}catch(Throwable e){report+="\n"+ShellBridge.root(e);}final String result=report;handler.post(()->{if(inspectView!=null)inspectView.setText(result);});});}
    private String deviceReport(){AudioManager a=getSystemService(AudioManager.class);StringBuilder b=new StringBuilder("AudioScope "+BuildConfig.VERSION_NAME+"\n"+Build.MANUFACTURER+" "+Build.MODEL+"\nAndroid "+Build.VERSION.RELEASE+" / SDK "+Build.VERSION.SDK_INT+"\nMode: "+a.getMode()+" (0 normal, 2 call, 3 communication)\nBackend: "+ScopeApp.backend+"\n");for(AudioDeviceInfo d:a.getDevices(AudioManager.GET_DEVICES_INPUTS | AudioManager.GET_DEVICES_OUTPUTS))b.append(d.isSource()?"INPUT ":"OUTPUT ").append(d.getProductName()).append(" • type ").append(d.getType()).append(" • rates ").append(Arrays.toString(d.getSampleRates())).append('\n');for(AudioRecordingConfiguration r:a.getActiveRecordingConfigurations())b.append("RECORD source ").append(r.getClientAudioSource()).append(" • silenced ").append(r.isClientSilenced()).append(" • ").append(r.getFormat()).append('\n');for(AudioPlaybackConfiguration p:a.getActivePlaybackConfigurations())b.append("PLAY ").append(p.getAudioAttributes()).append('\n');if(checkSelfPermission(Manifest.permission.READ_PHONE_STATE)==PackageManager.PERMISSION_GRANTED)try{b.append("Managed Telecom call: ").append(getSystemService(TelecomManager.class).isInManagedCall()).append('\n');}catch(Exception e){b.append("Telecom: ").append(e.getMessage());}else b.append("Telecom state unavailable; phone-state permission is optional.\n");return b.toString();}
    private void diagnosticExport(){ScopeApp.IO.execute(()->{try{File f=new File(ScopeApp.app.getExternalFilesDir(null),"diagnostics-"+System.currentTimeMillis()+".txt");String report=deviceReport()+"\n"+(ScopeApp.bridge==null?"Shell disconnected":ScopeApp.bridge.inspect())+"\n\nEVENTS\n"+ScopeApp.logText("");try(FileWriter w=new FileWriter(f)){w.write(report);}handler.post(()->share(f));}catch(Throwable e){ScopeApp.log("ERROR",e.toString());}});}
    private void repair(){if(CaptureService.active()){toast("Stop recording before repairing files");return;}ScopeApp.IO.execute(()->{int count=0;File[] dirs=ScopeApp.sessions().listFiles(File::isDirectory);if(dirs!=null)for(File d:dirs){File[] fs=d.listFiles((p,n)->n.endsWith(".wav"));if(fs!=null)for(File f:fs)try{WavFile.repair(f);count++;}catch(Exception e){ScopeApp.log("ERROR","Repair "+f.getName()+": "+e);}}ScopeApp.log("INFO","WAV header repair finished • "+count+" files");});}
    private void selfTest(){ScopeApp.IO.execute(()->{try{File d=new File(ScopeApp.sessions(),"self-test-"+System.currentTimeMillis());d.mkdirs();File one=new File(d,"440Hz.wav"),two=new File(d,"880Hz.wav");tone(one,440);tone(two,880);List<PcmRouter.Input> in=Arrays.asList(new PcmRouter.Input("a",one,0,1000000000,1),new PcmRouter.Input("b",two,100000000,1000000000,1));try{PcmRouter.export(new File(d,"stereo.wav"),in,48000,"a","b",false);PcmRouter.export(new File(d,"mix.wav"),in,48000,"","",true);}finally{for(PcmRouter.Input i:in)i.close();}MkaWriter.export(new File(d,"multitrack.mka"),Arrays.asList(new MkaWriter.Track("440 Hz test tone",one,48000,1,0),new MkaWriter.Track("880 Hz delayed test tone",two,48000,1,100000000)));try(WavFile.Reader r=new WavFile.Reader(new File(d,"stereo.wav"))){if(r.channels!=2||r.frames!=52800)throw new IOException("Timeline self-test failed");}Exports.encode(one,"AAC",128000);Exports.encode(one,"Opus",128000);for(String filename:new String[]{"440Hz.m4a","440Hz.webm"}){MediaExtractor extractor=new MediaExtractor();try{extractor.setDataSource(new File(d,filename).getPath());if(extractor.getTrackCount()!=1)throw new IOException("Encoded test track missing");}finally{extractor.release();}}try(FileWriter w=new FileWriter(new File(d,"TEST-RESULT.txt"))){w.write("PASS: PCM16 WAV, two-source stereo, 100 ms alignment, normalized mix, two-track Matroska, AAC and Opus containers. These are generated test tones, not microphone recordings.\n");}ScopeApp.log("INFO","SELF-TEST PASS • WAV / stereo alignment / mix / MKA / AAC / Opus • "+d.getName());}catch(Throwable e){ScopeApp.log("ERROR","SELF-TEST FAILED: "+ShellBridge.root(e));}});}
    private void tone(File file,double frequency)throws IOException{try(WavFile wav=new WavFile(file,48000,1)){byte[] b=new byte[96000];for(int i=0;i<48000;i++){short v=(short)(Math.sin(2*Math.PI*frequency*i/48000)*8000);b[i*2]=(byte)v;b[i*2+1]=(byte)(v>>>8);}wav.write(b,b.length);}}
    private void settings(){
        body.addView(title("Settings"));body.addView(text("A dedicated place for setup, capture, and diagnostics.",13,MUTED));section("APPEARANCE");
        LinearLayout appearance=card();appearance.addView(text("Dark Material You",17,INK));appearance.addView(text("Choose an accent or follow Android’s wallpaper palette.",12,MUTED));String current=ScopeApp.prefs().getString("accent","Purple");int colorIndex=0;for(int i=0;i<ThemePalette.NAMES.length;i++)if(ThemePalette.NAMES[i].equals(current))colorIndex=i;Spinner colors=spinner(ThemePalette.NAMES,colorIndex);colors.setOnItemSelectedListener(listener(index->{String chosen=ThemePalette.NAMES[index];if(!chosen.equals(ScopeApp.prefs().getString("accent","Purple"))){ScopeApp.prefs().edit().putString("accent",chosen).apply();handler.post(this::render);}}));appearance.addView(colors);LinearLayout swatches=horizontal();int[] tones={0xffbe9bff,0xffd0bcff,0xffa2c9ff,0xff89dfc5,0xffffb1ce,0xfff5cd87};for(int i=0;i<tones.length;i++){final int index=i;TextView dot=text("●",26,tones[i]);dot.setContentDescription(ThemePalette.NAMES[i]+" accent");dot.setGravity(Gravity.CENTER);dot.setOnClickListener(v->{ScopeApp.prefs().edit().putString("accent",ThemePalette.NAMES[index]).apply();render();});swatches.addView(dot,new LinearLayout.LayoutParams(0,dp(52),1));}appearance.addView(swatches);body.addView(appearance);section("PRIVILEGED CAPTURE");
        LinearLayout helper=card();helper.addView(text("Shizuku / Shevery",17,INK));helper.addView(text("Authorize a running shell service. Android/OEM restrictions still apply.",12,MUTED));helper.addView(button("Connect Shizuku / Shevery",ACCENT,()->{if(!settingsEditable())return;ScopeApp.app.connectShizuku();}));helper.addView(button("Open helper manager",CARD,()->{Intent i=getPackageManager().getLaunchIntentForPackage("com.hamondev.shevery");if(i==null)i=getPackageManager().getLaunchIntentForPackage("moe.shizuku.privileged.api");if(i!=null)startActivity(i);else toast("Install Shizuku or Shevery, then start its service");}));body.addView(helper);
        LinearLayout adb=card();adb.addView(text("Embedded ADB • no laptop",17,INK));adb.addView(text("Enable Wireless debugging. Pair using the six-digit code and pairing port, then use the connection port from Android's main Wireless debugging page. Pairing and recording stay on this phone.",12,MUTED));
        EditText pairPort=input("Pairing port","",true),code=input("Six-digit pairing code","",true);adb.addView(pairPort);adb.addView(code);adb.addView(button("Pair this phone",CARD,()->{if(!settingsEditable())return;try{EmbeddedAdb.pairDevice(Integer.parseInt(pairPort.getText().toString()),code.getText().toString());code.setText("");}catch(Exception e){toast("Enter a valid pairing port");}}));EditText connectPort=input("Connection port",ScopeApp.prefs().getString("adbPort",""),true);adb.addView(connectPort);adb.addView(button("Connect & start offline daemon",ACCENT,()->{if(!settingsEditable())return;try{int port=Integer.parseInt(connectPort.getText().toString());if(port<1||port>65535)throw new NumberFormatException();ScopeApp.prefs().edit().putString("adbPort",String.valueOf(port)).apply();EmbeddedAdb.launch(port);}catch(Exception e){toast("Enter the connection port from Android settings");}}));adb.addView(button("Open Developer options",CARD,()->startActivity(new Intent(Settings.ACTION_APPLICATION_DEVELOPMENT_SETTINGS))));
        adb.addView(text("Once the daemon connects, Binder capture continues without Wi-Fi. A reboot ends the daemon. The option below also allows restarting a killed daemon off Wi-Fi until reboot.",12,MUTED));adb.addView(button("Enable off-Wi-Fi daemon restart",CARD,()->{if(!settingsEditable())return;new AlertDialog.Builder(this).setTitle("Enable ADB TCP restart?").setMessage("ADB will restart and listen on port 5555, potentially on network interfaces as well as loopback. This may stop Shizuku. Android still requires an authorized ADB key. Use Disable below to close it. This clears after reboot.").setPositiveButton("Enable",(d,w)->EmbeddedAdb.enableOfflineRestart()).setNegativeButton("Cancel",null).show();}));two(adb,button("Restart via port 5555",CARD,()->{if(settingsEditable())EmbeddedAdb.launch(5555);}),button("Disable TCP listener",CARD,()->{if(settingsEditable())EmbeddedAdb.disableOfflineRestart();}));body.addView(adb);
        LinearLayout lifecycle=card();two(lifecycle,button("Disarm all policies",CARD,()->{if(!settingsEditable())return;ScopeApp.IO.execute(()->{try{if(ScopeApp.bridge!=null)ScopeApp.bridge.disarm();ScopeApp.log("INFO","Playback policies disarmed");}catch(Exception e){ScopeApp.log("ERROR",e.toString());}});}),button("Stop shell daemon",CARD,()->{if(!settingsEditable())return;ScopeApp.IO.execute(()->{try{if(ScopeApp.bridge!=null)ScopeApp.bridge.shutdown();}catch(Exception ignored){}ScopeApp.bridge=null;ScopeApp.backend="Not connected";});}));body.addView(lifecycle);
        section("CAPTURE & FILES");LinearLayout capture=card();choice(capture,"Sample rate",new String[]{"16,000 Hz","24,000 Hz","44,100 Hz","48,000 Hz"},"rate",new int[]{16000,24000,44100,48000},48000);choice(capture,"Capture channels",new String[]{"Mono","Stereo"},"channels",new int[]{1,2},1);stringChoice(capture,"Additional encoded copies",new String[]{"WAV","AAC","Opus"},"codec","WAV");choice(capture,"Encoded bitrate",new String[]{"64 kbps","128 kbps","192 kbps","256 kbps"},"bitrate",new int[]{64000,128000,192000,256000},128000);toggle(capture,"Save raw PCM too","Headerless PCM16 with JSON timing sidecars","raw",false);toggle(capture,"Keep CPU awake while recording","Background capture wake lock, capped at 12 hours","wakelock",true);numberSetting(capture,"Session limit in minutes • 0 = unlimited","maxMinutes",0,0,720);numberSetting(capture,"Playback UID filter • −1 = all apps","uidFilter",-1,-1,999999);capture.addView(text("Files: Android/data/dev.audioscope/files/sessions\nShare a session ZIP from the library to copy it anywhere.",11,MUTED));body.addView(capture);
        section("SIGNAL HEALTH");LinearLayout health=card();numberSetting(health,"Silence threshold • dBFS","silenceDb",-60,-120,-10);numberSetting(health,"Silence grace period • seconds","silenceSeconds",5,1,60);toggle(health,"Signal-aware carrier fallback","Try uplink/downlink, then communication playback + mic. Preserve all attempted tracks.","fallback",false);health.addView(button("Allow optional Telecom state diagnostics",CARD,()->requestPermissions(new String[]{Manifest.permission.READ_PHONE_STATE},23)));body.addView(health);
        section("ABOUT & SOURCE");LinearLayout about=card();about.addView(text("AudioScope 0.1.0 • experimental device build",16,INK));about.addView(text("Local capture and processing. No accounts, uploads, analytics, or cloud dependency. Network permission supports on-device ADB only. Use recordings where you have permission to record.",12,MUTED));about.addView(text("This software is an independently redesigned fork / edited derivative of capture and daemon components from CallVault and ShizuCallRecorder. GPLv3-or-later with upstream Section 7 terms. No warranty.",12,MUTED));about.addView(button("ShizuCallRecorder • original source",CARD,()->openUrl("https://github.com/kitsumed/ShizuCallRecorder")));about.addView(button("CallVault • capture reference",CARD,()->openUrl("https://github.com/madkongo/CallVault")));about.addView(button("Shevery • optional privilege manager",CARD,()->openUrl("https://github.com/HmnDev-Tech/shevery")));body.addView(about);
    }
    private boolean settingsEditable(){if(CaptureService.active()||CaptureService.instance!=null&&CaptureService.stopping){toast("Stop and finalize the session before changing setup or routing");return false;}return true;}
    private EditText input(String hint,String value,boolean numeric){EditText e=new EditText(this);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setTextSize(13);e.setSingleLine(true);e.setHint(hint);e.setText(value);e.setBackgroundTintList(android.content.res.ColorStateList.valueOf(ACCENT));e.setInputType(numeric?android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED:android.text.InputType.TYPE_CLASS_TEXT);return e;}
    private Spinner spinner(String[] labels,int selected){Spinner s=new Spinner(this);ArrayAdapter<String> adapter=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels);s.setAdapter(adapter);s.setSelection(selected);return s;}
    private void toggle(LinearLayout c,String label,String detail,String key,boolean fallback){com.google.android.material.materialswitch.MaterialSwitch s=new com.google.android.material.materialswitch.MaterialSwitch(this);s.setText(label);s.setTextColor(INK);s.setTextSize(14);s.setPadding(0,dp(8),0,dp(6));s.setChecked(ScopeApp.prefs().getBoolean(key,fallback));s.setEnabled(!CaptureService.active());s.setThumbTintList(android.content.res.ColorStateList.valueOf(ACCENT));s.setOnCheckedChangeListener((v,b)->ScopeApp.prefs().edit().putBoolean(key,b).apply());c.addView(s);c.addView(text(detail,11,MUTED));}
    private void choice(LinearLayout c,String label,String[] labels,String key,int[] values,int fallback){c.addView(text(label,12,MUTED));int value=ScopeApp.prefs().getInt(key,fallback),index=0;for(int i=0;i<values.length;i++)if(values[i]==value)index=i;Spinner s=spinner(labels,index);s.setEnabled(!CaptureService.active());s.setOnItemSelectedListener(listener(position->{int old=ScopeApp.prefs().getInt(key,fallback);ScopeApp.prefs().edit().putInt(key,values[position]).apply();if(old!=values[position])disarmAfterFormatChange();}));c.addView(s);}
    private void stringChoice(LinearLayout c,String label,String[] labels,String key,String fallback){c.addView(text(label,12,MUTED));String value=ScopeApp.prefs().getString(key,fallback);int index=0;for(int i=0;i<labels.length;i++)if(labels[i].equals(value))index=i;Spinner s=spinner(labels,index);s.setEnabled(!CaptureService.active());s.setOnItemSelectedListener(listener(position->ScopeApp.prefs().edit().putString(key,labels[position]).apply()));c.addView(s);}
    private AdapterView.OnItemSelectedListener listener(java.util.function.IntConsumer action){return new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> a){}public void onItemSelected(AdapterView<?> a,View v,int p,long id){action.accept(p);}};}
    private void sourceSpinner(LinearLayout c,String label,String key,String fallback){c.addView(text(label,12,MUTED));String[] names=Source.ALL.stream().map(s->s.title).toArray(String[]::new);int index=0;for(int i=0;i<Source.ALL.size();i++)if(Source.ALL.get(i).id.equals(ScopeApp.prefs().getString(key,fallback)))index=i;Spinner s=spinner(names,index);s.setEnabled(!CaptureService.active());s.setOnItemSelectedListener(listener(p->ScopeApp.prefs().edit().putString(key,Source.ALL.get(p).id).apply()));c.addView(s);}
    private void numberSetting(LinearLayout c,String label,String key,int fallback,int min,int max){c.addView(text(label,12,MUTED));EditText e=input(label,String.valueOf(ScopeApp.prefs().getInt(key,fallback)),true);e.setEnabled(!CaptureService.active());e.setOnFocusChangeListener((v,focus)->{if(!focus){try{int n=Integer.parseInt(e.getText().toString());if(n<min||n>max)throw new NumberFormatException();ScopeApp.prefs().edit().putInt(key,n).apply();if(key.equals("uidFilter"))disarmAfterFormatChange();}catch(Exception ex){e.setText(String.valueOf(ScopeApp.prefs().getInt(key,fallback)));toast("Use a value from "+min+" to "+max);}}});c.addView(e);}
    private void disarmAfterFormatChange(){ScopeApp.IO.execute(()->{try{if(ScopeApp.bridge!=null)ScopeApp.bridge.disarm();}catch(Exception ignored){}});}
    private void prompt(String title,String initial,java.util.function.Consumer<String> action){EditText e=input(title,initial,false);new AlertDialog.Builder(this).setTitle(title).setView(e).setPositiveButton("Save",(d,w)->{String s=e.getText().toString().trim();if(!s.isEmpty())action.accept(s);}).setNegativeButton("Cancel",null).show();}
    private void savePreset(String name){if(!settingsEditable())return;try{JSONObject j=new JSONObject();j.put("sources",new JSONArray(selected));JSONObject settings=new JSONObject();for(Map.Entry<String,?> e:ScopeApp.prefs().getAll().entrySet()){String k=e.getKey();if(k.equals("rate")||k.equals("channels")||k.equals("uidFilter")||k.equals("codec")||k.equals("bitrate")||k.equals("raw")||k.equals("stereo")||k.equals("mix")||k.equals("mka")||k.startsWith("route")||k.startsWith("gain_")||k.startsWith("mute_")||k.startsWith("format_"))settings.put(k,e.getValue());}j.put("settings",settings);JSONObject all=new JSONObject(ScopeApp.prefs().getString("presets","{}"));all.put(name,j);ScopeApp.prefs().edit().putString("presets",all.toString()).apply();toast("Saved "+name);}catch(Exception e){toast(e.toString());}}
    private void loadPreset(){if(!settingsEditable())return;try{JSONObject all=new JSONObject(ScopeApp.prefs().getString("presets","{}"));List<String> names=new ArrayList<>();all.keys().forEachRemaining(names::add);if(names.isEmpty()){toast("Save a preset first");return;}new AlertDialog.Builder(this).setTitle("Load capture preset").setItems(names.toArray(new String[0]),(d,w)->{try{JSONObject j=all.getJSONObject(names.get(w));selected.clear();JSONArray a=j.getJSONArray("sources");for(int i=0;i<a.length();i++)selected.add(a.getString(i));saveSelection();JSONObject prefs=j.getJSONObject("settings");SharedPreferences.Editor edit=ScopeApp.prefs().edit();Iterator<String> keys=prefs.keys();while(keys.hasNext()){String key=keys.next();Object v=prefs.get(key);if(v instanceof Boolean)edit.putBoolean(key,(Boolean)v);else if(v instanceof Integer)edit.putInt(key,(Integer)v);else if(v instanceof Number)edit.putFloat(key,((Number)v).floatValue());else edit.putString(key,v.toString());}edit.apply();disarmAfterFormatChange();render();}catch(Exception e){toast(e.toString());}}).show();}catch(Exception e){toast(e.toString());}}
    private void showText(String title,String content){ScrollView s=new ScrollView(this);TextView t=text(content,12,INK);t.setPadding(dp(16),dp(12),dp(16),dp(12));t.setTextIsSelectable(true);s.addView(t);new AlertDialog.Builder(this).setTitle(title).setView(s).setPositiveButton("Close",null).show();}
    private void setIfChanged(TextView view,CharSequence value){if(!view.getText().toString().contentEquals(value))view.setText(value);}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
    private void openUrl(String url){startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}
}
